### ISSUE TITLE
src/release.py missing in the PyPI package

### ISSUE THREAD

**Issue by petrrr** [SpotlightKid/threadpool#2]
I just realized that the file is missing in the PyPI package, so probably something went wrong during the release process.

**Comment by SpotlightKid** [comment]
Dang, forgot to include the file in `MANIFEST.in`. It is not needed for the installed module, but for the `setup.py install` process. Thanks for the headsup!

Fixed in  b09be8d and released 1.3.2.

**Comment by petrrr** [comment]
Great! 
... and thanks for the quick fix.
