### ISSUE TITLE
exception raised during interpreter shutdown

### ISSUE THREAD

**Issue by zhangyangyu** [SpotlightKid/threadpool#3]
Hi Christopher :-)

I'd like report a problem(not a bug) about threadpool, I know this module is obsolete but obviously there are people still using it, such as my colleagues. 

My colleague uses threadpool just like the example you give. But then we possibly could get an exception like:
```
Exception in thread Thread-18 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
   File "/apkg/spb/packages/common_base/threadpool.py", line 149, in run
 <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

I could reproduce this exception using a script like this:
```
import time
import random
import threadpool

def func(x):
    time.sleep(random.random())
pool = threadpool.ThreadPool(3, poll_timeout=random.random())
for req in threadpool.makeRequests(func, range(3), None, None):
    pool.putRequest(req)
pool.wait()
time.sleep(random.random())
```
I run it 1000 times and succeed reproducing several times.

I don't think there is any bug in threadpool, but I think the example is not perfect. It doesn't clean up the daemon threads so any users simply following the guide could get exceptions possibly at shutdown, though this usually can't cause any problem.

**Comment by SpotlightKid** [comment]
There is a remark in the readme directly after the example you cite, which refers the reader to the longer example in the module source code. This example shows how clean up properly.

Otherwise, I'm sorry to say, that I don't really want to put any more effort into this module. I think there are far superior solutions now available everywhere.
